// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEQSlSnqMpu95FaDZsLYeLGHgM2ocAYg',
    appId: '1:723508172461:web:78712a8eb99fbf74301824',
    messagingSenderId: '723508172461',
    projectId: 'tiktok-clone-a5385',
    authDomain: 'tiktok-clone-a5385.firebaseapp.com',
    storageBucket: 'tiktok-clone-a5385.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5pAogRVL8PCnL7dFVer0MNZML3usRH94',
    appId: '1:723508172461:android:c3375c391ddf04fd301824',
    messagingSenderId: '723508172461',
    projectId: 'tiktok-clone-a5385',
    storageBucket: 'tiktok-clone-a5385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6jDnsoGuZbkT4NC8SsItrX62G-bNhWc',
    appId: '1:723508172461:ios:c45c6ad80726970a301824',
    messagingSenderId: '723508172461',
    projectId: 'tiktok-clone-a5385',
    storageBucket: 'tiktok-clone-a5385.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6jDnsoGuZbkT4NC8SsItrX62G-bNhWc',
    appId: '1:723508172461:ios:a8b36d4db2a2f9a2301824',
    messagingSenderId: '723508172461',
    projectId: 'tiktok-clone-a5385',
    storageBucket: 'tiktok-clone-a5385.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
